(() => {
'use strict';
const STORAGE='lcmc_state_v10';
const LEGACY={hours:'lcmc_hours_v3',farms:'lcmc_farms',settings:'lcmc_settings',expenses:'lcmc_expenses_v1',invoices:'lcmc_invoices_v1'};
const $=id=>document.getElementById(id), $$=sel=>[...document.querySelectorAll(sel)];
const state={entries:[],farms:[],expenses:[],invoices:[],settings:{defaultRate:25,contributionRate:22,goal:3000,businessName:'Le Coup de Main Du Coin',businessSiret:'',businessPhone:'',businessAddress:''}};
let viewDate=new Date(new Date().getFullYear(),new Date().getMonth(),1), activeView='home', editingEntryDate=null,editingFarmId=null,editingExpenseId=null;

const uid=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const parseDate=s=>new Date(`${s}T00:00:00`);
const money=n=>Number(n||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const minutes=(a,b)=>{if(!a||!b)return 0;let [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number),x=ah*60+am,y=bh*60+bm;if(y<x)y+=1440;return Math.max(0,y-x)};
const fmt=m=>{m=Math.max(0,Math.round(Number(m)||0));return `${Math.floor(m/60)}h${String(m%60).padStart(2,'0')}`};
const farmById=id=>state.farms.find(f=>f.id===id);
const farmName=id=>farmById(id)?.name||'Exploitation non renseignée';
const currentMonth=(arr=state.entries)=>arr.filter(x=>{const d=parseDate(x.date);return d.getFullYear()===viewDate.getFullYear()&&d.getMonth()===viewDate.getMonth()});
const currentExpenses=()=>state.expenses.filter(x=>{const d=parseDate(x.date);return d.getFullYear()===viewDate.getFullYear()&&d.getMonth()===viewDate.getMonth()});
const caOf=x=>(Number(x.dur)||0)/60*(Number(x.rate)||0);
const monthMetrics=(date=viewDate)=>{const y=date.getFullYear(),m=date.getMonth(),e=state.entries.filter(x=>{const d=parseDate(x.date);return d.getFullYear()===y&&d.getMonth()===m}),mins=e.reduce((s,x)=>s+(Number(x.dur)||0),0),ca=e.reduce((s,x)=>s+caOf(x),0),days=new Set(e.map(x=>x.date)).size,expenses=state.expenses.filter(x=>{const d=parseDate(x.date);return d.getFullYear()===y&&d.getMonth()===m}).reduce((s,x)=>s+Number(x.amount||0),0),social=ca*(Number(state.settings.contributionRate||0)/100);return {entries:e,mins,ca,days,avg:days?mins/days:0,expenses,social,profit:ca-expenses-social}};
function trend(now,prev){if(!prev)return now?'Nouveau mois':'Nouveau mois';const pct=(now-prev)/prev*100;return `${pct>=0?'▲':'▼'} ${Math.abs(pct).toFixed(0)}%`}

function load(){
  try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved&&saved.version>=10){Object.assign(state,{...state,...saved.data,settings:{...state.settings,...(saved.data?.settings||{})}});normalize();return}}catch{}
  try{state.entries=JSON.parse(localStorage.getItem(LEGACY.hours)||'[]')||[]}catch{}
  try{state.farms=JSON.parse(localStorage.getItem(LEGACY.farms)||'[]')||[]}catch{}
  try{state.expenses=JSON.parse(localStorage.getItem(LEGACY.expenses)||'[]')||[]}catch{}
  try{state.invoices=JSON.parse(localStorage.getItem(LEGACY.invoices)||'[]')||[]}catch{}
  try{state.settings={...state.settings,...(JSON.parse(localStorage.getItem(LEGACY.settings)||'{}')||{})}}catch{}
  normalize(); save();
}
function normalize(){
  state.entries=(Array.isArray(state.entries)?state.entries:[]).map(x=>({...x,id:x.id||uid('day'),dur:Number(x.dur)||minutes(x.sm,x.em)+minutes(x.sa,x.ea),rate:Number(x.rate)||Number(state.settings.defaultRate)||25}));
  state.farms=Array.isArray(state.farms)?state.farms:[];state.expenses=Array.isArray(state.expenses)?state.expenses:[];state.invoices=Array.isArray(state.invoices)?state.invoices:[];
}
function save(){localStorage.setItem(STORAGE,JSON.stringify({version:11,updatedAt:new Date().toISOString(),data:state}));localStorage.setItem(LEGACY.hours,JSON.stringify(state.entries));localStorage.setItem(LEGACY.farms,JSON.stringify(state.farms));localStorage.setItem(LEGACY.expenses,JSON.stringify(state.expenses));localStorage.setItem(LEGACY.invoices,JSON.stringify(state.invoices));localStorage.setItem(LEGACY.settings,JSON.stringify(state.settings))}

function showView(name){activeView=name;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'});render()}
function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(id){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true');document.body.style.overflow=''}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2200)}

function renderCalendar(target){const box=$(target),y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate(),prevLast=new Date(y,m,0).getDate(),today=iso(new Date()),worked=new Set(currentMonth().map(x=>x.date));let html='';for(let i=offset-1;i>=0;i--){html+=`<button class="cal-day other" disabled>${prevLast-i}</button>`}for(let d=1;d<=last;d++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,cl=['cal-day',worked.has(ds)?'worked':'',ds===today?'today':''].filter(Boolean).join(' ');html+=`<button class="${cl}" data-date="${ds}">${d}</button>`}let n=offset+last,next=1;while(n%7){html+=`<button class="cal-day other" disabled>${next++}</button>`;n++}box.innerHTML=html}
function entryCard(x){const d=parseDate(x.date),slots=[x.sm&&x.em?`${x.sm}–${x.em}`:'',x.sa&&x.ea?`${x.sa}–${x.ea}`:''].filter(Boolean).join(' · ');return `<article class="entry" data-entry-date="${x.date}"><div class="date-box"><b>${d.getDate()}</b><small>${d.toLocaleDateString('fr-FR',{weekday:'short'})}</small></div><div class="entry-main"><b>${esc(farmName(x.farmId)||x.client)}</b><small>${esc(slots||'Horaires incomplets')}${x.notes?' · '+esc(x.notes):''}</small></div><div class="entry-side"><b>${fmt(x.dur)}</b><small>${money(caOf(x))}</small></div></article>`}
function farmStats(id){const a=currentMonth().filter(x=>x.farmId===id);return {mins:a.reduce((s,x)=>s+x.dur,0),ca:a.reduce((s,x)=>s+caOf(x),0),days:new Set(a.map(x=>x.date)).size}}
function farmCard(f){const s=farmStats(f.id);return `<article class="farm-card"><div class="farm-top"><div class="farm-icon">🌾</div><div class="grow"><b>${esc(f.name)}</b><small>${s.days} jour${s.days>1?'s':''} ce mois${f.rate?` · ${money(f.rate)}/h`:''}</small></div><div class="card-actions"><button class="icon-btn" data-edit-farm="${f.id}">✎</button></div></div><div class="pill-row"><span class="pill">◷ ${fmt(s.mins)}</span><span class="pill">€ ${money(s.ca)}</span></div></article>`}
function expenseCard(x){const d=parseDate(x.date);return `<article class="expense-card"><div class="expense-top"><div class="grow"><b>${esc(x.label||x.category||'Dépense')}</b><small>${d.toLocaleDateString('fr-FR')} · ${esc(x.category||'Autre')}</small></div><span class="amount">− ${money(x.amount)}</span><button class="icon-btn" data-edit-expense="${x.id}">✎</button></div></article>`}
function statusText(s){return s==='paid'?'Payée':s==='sent'?'Envoyée':'Brouillon'}
function invoiceCard(x){return `<article class="invoice-card"><div class="invoice-top"><div class="grow"><b>Facture ${esc(x.number)}</b><small>${esc(farmName(x.farmId))} · ${fmt(x.mins)} · ${money(x.total)}</small></div><button class="invoice-status ${x.status||'draft'}" data-cycle-invoice="${x.id}">${statusText(x.status)}</button><button class="icon-btn" data-print-invoice="${x.id}">↗</button></div></article>`}

function render(){const td=$('todayLabel');if(td)td.textContent=new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}).replace(/^./,c=>c.toUpperCase());const m=monthMetrics(),prevDate=new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1),p=monthMetrics(prevDate);$('homeMonthChip').textContent=viewDate.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});$('statHours').textContent=fmt(m.mins);$('statCA').textContent=money(m.ca);$('statDays').textContent=m.days;$('statAvg').textContent=fmt(m.avg);$('trendHours').textContent=trend(m.mins,p.mins);$('trendCA').textContent=trend(m.ca,p.ca);$('homeProfit').textContent=money(m.profit);$('homeCA').textContent=money(m.ca);$('homeExpenses').textContent=money(m.expenses);$('homeSocial').textContent=money(m.social);renderCalendar('homeCalendar');renderCalendar('hoursCalendar');$('hoursMonthLabel').textContent=viewDate.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});$('homeEntries').innerHTML=m.entries.length?m.entries.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(entryCard).join(''):'<div class="empty">Aucune journée saisie ce mois-ci.</div>';renderHistory();renderFarms();renderFinance(m);populateSettings();populateSelects()}
function renderHistory(){const q=($('historySearch')?.value||'').trim().toLowerCase(),fid=$('historyFarm')?.value||'';const arr=currentMonth().filter(x=>(!fid||x.farmId===fid)&&(!q||farmName(x.farmId).toLowerCase().includes(q)||(x.notes||'').toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));$('historyList').innerHTML=arr.length?arr.map(entryCard).join(''):'<div class="empty">Aucune journée correspondant à ce filtre.</div>'}
function renderFarms(){$('farmList').innerHTML=state.farms.length?state.farms.map(farmCard).join(''):'<div class="empty">Ajoute ta première exploitation pour commencer.</div>'}
function renderFinance(m){$('financeMonthLabel').textContent=viewDate.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});$('finProfit').textContent=money(m.profit);$('finCA').textContent=money(m.ca);$('finExpenses').textContent=money(m.expenses);$('finSocial').textContent=money(m.social);$('finRate').textContent=m.mins?money(m.ca/(m.mins/60))+'/h':'0,00 €/h';const goal=Number(state.settings.goal||3000),pct=goal?Math.min(100,m.ca/goal*100):0;$('goalText').textContent=`${money(m.ca)} / ${money(goal)}`;$('goalPct').textContent=`${Math.round(pct)}%`;$('goalBar').style.width=`${pct}%`;$('expenseList').innerHTML=currentExpenses().length?currentExpenses().slice().sort((a,b)=>b.date.localeCompare(a.date)).map(expenseCard).join(''):'<div class="empty">Aucune dépense ce mois-ci.</div>';$('invoiceList').innerHTML=state.invoices.length?state.invoices.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(invoiceCard).join(''):'<div class="empty">Aucune facture créée.</div>';drawChart()}
function populateSettings(){const s=state.settings;$('defaultRate').value=s.defaultRate??25;$('contributionRate').value=s.contributionRate??22;$('monthlyGoal').value=s.goal??3000;$('businessName').value=s.businessName||'';$('businessSiret').value=s.businessSiret||'';$('businessPhone').value=s.businessPhone||'';$('businessAddress').value=s.businessAddress||''}
function populateSelects(){const opts=state.farms.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');['entryFarm','invoiceFarm'].forEach(id=>{const el=$(id),v=el.value;el.innerHTML=`<option value="">Choisir…</option>${opts}`;if([...el.options].some(o=>o.value===v))el.value=v});const h=$('historyFarm'),hv=h.value;h.innerHTML=`<option value="">Toutes les exploitations</option>${opts}`;if([...h.options].some(o=>o.value===hv))h.value=hv}
function drawChart(){const c=$('financeChart'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||480,h=180;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const months=[];for(let i=5;i>=0;i--){const d=new Date(viewDate.getFullYear(),viewDate.getMonth()-i,1),m=monthMetrics(d);months.push({label:d.toLocaleDateString('fr-FR',{month:'short'}).replace('.',''),...m})}const max=Math.max(1,...months.flatMap(x=>[x.ca,Math.max(0,x.profit)]));const base=h-28,top=10,barW=Math.max(12,(w-36)/months.length/2.5),group=(w-36)/months.length;ctx.font='10px system-ui';ctx.textAlign='center';months.forEach((x,i)=>{const cx=18+group*i+group/2,ch=(x.ca/max)*(base-top),ph=(Math.max(0,x.profit)/max)*(base-top);ctx.fillStyle='#168bd6';ctx.fillRect(cx-barW-2,base-ch,barW,ch);ctx.fillStyle='#2ea653';ctx.fillRect(cx+2,base-ph,barW,ph);ctx.fillStyle='#718596';ctx.fillText(x.label,cx,h-8)});ctx.textAlign='left';ctx.fillStyle='#168bd6';ctx.fillRect(8,2,10,7);ctx.fillStyle='#49677e';ctx.fillText('CA',22,9);ctx.fillStyle='#2ea653';ctx.fillRect(50,2,10,7);ctx.fillStyle='#49677e';ctx.fillText('Résultat',64,9)}

function openEntry(date=iso(new Date())){editingEntryDate=date;const x=state.entries.find(e=>e.date===date);$('entryTitle').textContent=x?'Modifier ma journée':'Saisir mes heures';$('entryDate').value=date;populateSelects();$('entryFarm').value=x?.farmId||'';$('morningStart').value=x?.sm||'';$('morningEnd').value=x?.em||'';$('afternoonStart').value=x?.sa||'';$('afternoonEnd').value=x?.ea||'';$('entryRate').value=x?.rate??(farmById(x?.farmId)?.rate||state.settings.defaultRate);$('entryNotes').value=x?.notes||'';$('deleteEntryBtn').classList.toggle('hidden',!x);updateEntryPreview();openModal('entryModal')}
function updateEntryPreview(){const dur=minutes($('morningStart').value,$('morningEnd').value)+minutes($('afternoonStart').value,$('afternoonEnd').value),rate=Number($('entryRate').value||0);$('entryLiveTotal').textContent=`${fmt(dur)} · ${money(dur/60*rate)}`}
function saveEntry(){const date=$('entryDate').value,farmId=$('entryFarm').value;if(!date)return alert('Choisis une date.');if(!farmId)return alert('Choisis une exploitation.');const sm=$('morningStart').value,em=$('morningEnd').value,sa=$('afternoonStart').value,ea=$('afternoonEnd').value,dur=minutes(sm,em)+minutes(sa,ea);if(!dur)return alert('Saisis au moins une plage horaire complète.');const rate=Number($('entryRate').value);if(!(rate>=0))return alert('Tarif invalide.');const data={id:state.entries.find(e=>e.date===editingEntryDate)?.id||uid('day'),date,farmId,sm,em,sa,ea,dur,rate,notes:$('entryNotes').value.trim()};const idx=state.entries.findIndex(e=>e.date===editingEntryDate);if(idx>=0)state.entries[idx]=data;else state.entries.push(data);save();closeModal('entryModal');toast('Journée enregistrée ✓');render()}
function deleteEntry(){if(!editingEntryDate||!confirm('Supprimer cette journée ?'))return;state.entries=state.entries.filter(e=>e.date!==editingEntryDate);save();closeModal('entryModal');toast('Journée supprimée');render()}
function openFarm(id=null){editingFarmId=id;const f=farmById(id);$('farmTitle').textContent=f?'Modifier l’exploitation':'Ajouter une exploitation';$('farmNameInput').value=f?.name||'';$('farmRateInput').value=f?.rate??'';$('farmNoteInput').value=f?.note||'';$('deleteFarmBtn').classList.toggle('hidden',!f);openModal('farmModal')}
function saveFarm(){const name=$('farmNameInput').value.trim();if(!name)return alert('Indique le nom de l’exploitation.');const rateRaw=$('farmRateInput').value.trim(),data={id:editingFarmId||uid('farm'),name,rate:rateRaw===''?null:Number(rateRaw),note:$('farmNoteInput').value.trim()};const i=state.farms.findIndex(f=>f.id===editingFarmId);if(i>=0)state.farms[i]=data;else state.farms.push(data);save();closeModal('farmModal');toast('Exploitation enregistrée ✓');render()}
function deleteFarm(){if(!editingFarmId||!confirm('Supprimer cette exploitation ? Les journées resteront conservées.'))return;state.farms=state.farms.filter(f=>f.id!==editingFarmId);save();closeModal('farmModal');toast('Exploitation supprimée');render()}
function openExpense(id=null){editingExpenseId=id;const x=state.expenses.find(e=>e.id===id);$('expenseTitle').textContent=x?'Modifier la dépense':'Ajouter une dépense';$('expenseDate').value=x?.date||iso(new Date());$('expenseAmount').value=x?.amount??'';$('expenseCategory').value=x?.category||'Carburant';$('expenseLabel').value=x?.label||'';$('expenseNote').value=x?.note||'';$('deleteExpenseBtn').classList.toggle('hidden',!x);openModal('expenseModal')}
function saveExpense(){const date=$('expenseDate').value,amount=Number($('expenseAmount').value);if(!date||!(amount>0))return alert('Indique une date et un montant supérieur à 0.');const data={id:editingExpenseId||uid('exp'),date,amount,category:$('expenseCategory').value,label:$('expenseLabel').value.trim(),note:$('expenseNote').value.trim()};const i=state.expenses.findIndex(x=>x.id===editingExpenseId);if(i>=0)state.expenses[i]=data;else state.expenses.push(data);save();closeModal('expenseModal');toast('Dépense enregistrée ✓');render()}
function deleteExpense(){if(!editingExpenseId||!confirm('Supprimer cette dépense ?'))return;state.expenses=state.expenses.filter(x=>x.id!==editingExpenseId);save();closeModal('expenseModal');toast('Dépense supprimée');render()}

function nextInvoiceNumber(){const y=new Date().getFullYear(),nums=state.invoices.filter(x=>String(x.number||'').startsWith(`${y}-`)).map(x=>Number(String(x.number).split('-')[1])||0);return `${y}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`}
function invoiceEntries(fid,start,end){return state.entries.filter(x=>x.farmId===fid&&x.date>=start&&x.date<=end).sort((a,b)=>a.date.localeCompare(b.date))}
function openInvoice(){populateSelects();$('invoiceStart').value=iso(new Date(viewDate.getFullYear(),viewDate.getMonth(),1));$('invoiceEnd').value=iso(new Date(viewDate.getFullYear(),viewDate.getMonth()+1,0));$('invoiceDate').value=iso(new Date());$('invoiceStatus').value='draft';$('invoicePreview').textContent='Sélectionne une exploitation.';openModal('invoiceModal');updateInvoicePreview()}
function updateInvoicePreview(){const fid=$('invoiceFarm').value,start=$('invoiceStart').value,end=$('invoiceEnd').value;if(!fid||!start||!end){$('invoicePreview').textContent='Sélectionne une exploitation et une période.';return}const a=invoiceEntries(fid,start,end),mins=a.reduce((s,x)=>s+x.dur,0),total=a.reduce((s,x)=>s+caOf(x),0);$('invoicePreview').textContent=`${a.length} journée${a.length>1?'s':''} · ${fmt(mins)} · ${money(total)}`}
function saveInvoice(){const fid=$('invoiceFarm').value,start=$('invoiceStart').value,end=$('invoiceEnd').value;if(!fid||!start||!end||end<start)return alert('Vérifie l’exploitation et la période.');const a=invoiceEntries(fid,start,end);if(!a.length)return alert('Aucune heure sur cette période.');const inv={id:uid('inv'),number:nextInvoiceNumber(),farmId:fid,start,end,date:$('invoiceDate').value||iso(new Date()),status:$('invoiceStatus').value,note:$('invoiceNote').value.trim(),mins:a.reduce((s,x)=>s+x.dur,0),total:a.reduce((s,x)=>s+caOf(x),0)};state.invoices.push(inv);save();closeModal('invoiceModal');toast(`Facture ${inv.number} créée ✓`);render();printInvoice(inv.id)}
function cycleInvoice(id){const x=state.invoices.find(v=>v.id===id);if(!x)return;x.status=x.status==='draft'?'sent':x.status==='sent'?'paid':'draft';save();render();toast(`Statut : ${statusText(x.status)}`)}
function printInvoice(id){const x=state.invoices.find(v=>v.id===id);if(!x)return;const f=farmById(x.farmId),a=invoiceEntries(x.farmId,x.start,x.end),rows=a.map(e=>`<tr><td>${parseDate(e.date).toLocaleDateString('fr-FR')}</td><td>${fmt(e.dur)}</td><td>${money(e.rate)}/h</td><td>${money(caOf(e))}</td></tr>`).join(''),s=state.settings,w=window.open('','_blank');if(!w)return alert('Autorise les fenêtres pop-up pour ouvrir la facture.');w.document.write(`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Facture ${esc(x.number)}</title><style>body{font-family:Arial,sans-serif;color:#163d5d;max-width:820px;margin:40px auto;padding:0 20px}header{display:flex;justify-content:space-between;gap:30px;border-bottom:3px solid #075da7;padding-bottom:20px}h1{color:#075da7;margin:0}.muted{color:#708497;font-size:13px;line-height:1.5}.client{margin:30px 0;padding:16px;background:#f1f7fb;border-radius:12px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #dce7ef;text-align:left;font-size:13px}th{background:#edf5fb}.total{text-align:right;font-size:24px;font-weight:bold;color:#075da7;margin-top:20px}.foot{margin-top:35px;font-size:11px;color:#738596}@media print{button{display:none}}</style></head><body><header><div><h1>${esc(s.businessName||'Le Coup de Main Du Coin')}</h1><div class="muted">${esc(s.businessAddress||'').replaceAll('\n','<br>')}${s.businessSiret?'<br>SIRET : '+esc(s.businessSiret):''}${s.businessPhone?'<br>Tél. : '+esc(s.businessPhone):''}</div></div><div><b>FACTURE ${esc(x.number)}</b><div class="muted">Date : ${parseDate(x.date).toLocaleDateString('fr-FR')}<br>Période : ${parseDate(x.start).toLocaleDateString('fr-FR')} au ${parseDate(x.end).toLocaleDateString('fr-FR')}</div></div></header><div class="client"><b>Client</b><br>${esc(f?.name||'Exploitation')}</div><table><thead><tr><th>Date</th><th>Durée</th><th>Tarif</th><th>Montant</th></tr></thead><tbody>${rows}</tbody></table><div class="total">Total : ${money(x.total)}</div><div class="foot">${esc(x.note||'Prestation de service agricole')}<br>TVA non applicable, art. 293 B du CGI — à adapter à ta situation fiscale réelle.</div><p><button onclick="window.print()">Imprimer / Enregistrer en PDF</button></p></body></html>`);w.document.close()}

function saveSettings(businessOnly=false){if(!businessOnly){state.settings.defaultRate=Math.max(0,Number($('defaultRate').value)||25);state.settings.contributionRate=Math.max(0,Number($('contributionRate').value)||0);state.settings.goal=Math.max(1,Number($('monthlyGoal').value)||3000)}state.settings.businessName=$('businessName').value.trim()||'Le Coup de Main Du Coin';state.settings.businessSiret=$('businessSiret').value.trim();state.settings.businessPhone=$('businessPhone').value.trim();state.settings.businessAddress=$('businessAddress').value.trim();save();toast('Réglages enregistrés ✓');render()}
function setGoal(){const v=prompt('Objectif de chiffre d’affaires mensuel (€)',state.settings.goal||3000);if(v===null)return;const n=Number(String(v).replace(',','.'));if(!(n>0))return alert('Montant invalide.');state.settings.goal=n;save();render();toast('Objectif mis à jour ✓')}
function exportBlob(content,type,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csv(rows){return '\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n')}
function exportHours(){const rows=[['Date','Exploitation','Matin début','Matin fin','Après-midi début','Après-midi fin','Heures','Tarif','CA','Notes'],...state.entries.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(x=>[x.date,farmName(x.farmId),x.sm,x.em,x.sa,x.ea,fmt(x.dur),x.rate,caOf(x).toFixed(2).replace('.',','),x.notes||''])];exportBlob(csv(rows),'text/csv;charset=utf-8',`LCMC_heures_${iso(new Date())}.csv`);toast('Export heures créé ✓')}
function exportFinance(){const rows=[['Date','Type','Catégorie / client','Libellé','Montant'],...state.entries.map(x=>[x.date,'CA',farmName(x.farmId),`Heures ${fmt(x.dur)}`,caOf(x).toFixed(2).replace('.',',')]),...state.expenses.map(x=>[x.date,'Dépense',x.category,x.label||'',(-Number(x.amount||0)).toFixed(2).replace('.',',')])].sort((a,b)=>a[0].localeCompare(b[0]));exportBlob(csv(rows),'text/csv;charset=utf-8',`LCMC_finances_${iso(new Date())}.csv`);toast('Export finances créé ✓')}
function exportBackup(){exportBlob(JSON.stringify({app:'LCMC',version:11,exportedAt:new Date().toISOString(),data:state},null,2),'application/json',`LCMC_sauvegarde_${iso(new Date())}.json`);toast('Sauvegarde créée ✓')}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result),src=d.data||d;if(!Array.isArray(src.entries)||!Array.isArray(src.farms))throw new Error('format');if(!confirm('Restaurer cette sauvegarde ? Les données actuelles seront remplacées.'))return;state.entries=src.entries||[];state.farms=src.farms||[];state.expenses=src.expenses||[];state.invoices=src.invoices||[];state.settings={...state.settings,...(src.settings||{})};normalize();save();render();toast('Sauvegarde restaurée ✓')}catch{alert('Fichier de sauvegarde LCMC invalide.')}};r.readAsText(file)}

function handleAction(a){if(a==='prev-month'){viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1);render()}else if(a==='next-month'){viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+1,1);render()}else if(a==='today-month'){const d=new Date();viewDate=new Date(d.getFullYear(),d.getMonth(),1);render()}else if(a==='goto-hours')showView('hours');else if(a==='goto-finance')showView('finance');else if(a==='add-entry')openEntry();else if(a==='save-entry')saveEntry();else if(a==='delete-entry')deleteEntry();else if(a==='add-farm')openFarm();else if(a==='save-farm')saveFarm();else if(a==='delete-farm')deleteFarm();else if(a==='add-expense')openExpense();else if(a==='save-expense')saveExpense();else if(a==='delete-expense')deleteExpense();else if(a==='add-invoice')openInvoice();else if(a==='save-invoice')saveInvoice();else if(a==='save-settings')saveSettings(false);else if(a==='save-business')saveSettings(true);else if(a==='set-goal')setGoal();else if(a==='export-hours')exportHours();else if(a==='export-finance')exportFinance();else if(a==='export-backup')exportBackup()}

document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)return showView(nav.dataset.nav);const act=e.target.closest('[data-action]');if(act)return handleAction(act.dataset.action);const close=e.target.closest('[data-close]');if(close)return closeModal(close.dataset.close);const day=e.target.closest('[data-date]');if(day)return openEntry(day.dataset.date);const entry=e.target.closest('[data-entry-date]');if(entry)return openEntry(entry.dataset.entryDate);const ef=e.target.closest('[data-edit-farm]');if(ef)return openFarm(ef.dataset.editFarm);const ee=e.target.closest('[data-edit-expense]');if(ee)return openExpense(ee.dataset.editExpense);const ci=e.target.closest('[data-cycle-invoice]');if(ci)return cycleInvoice(ci.dataset.cycleInvoice);const pi=e.target.closest('[data-print-invoice]');if(pi)return printInvoice(pi.dataset.printInvoice);if(e.target.classList.contains('modal'))closeModal(e.target.id)});
['morningStart','morningEnd','afternoonStart','afternoonEnd','entryRate'].forEach(id=>$(id).addEventListener('input',updateEntryPreview));$('entryFarm').addEventListener('change',()=>{const f=farmById($('entryFarm').value);if(f?.rate!=null)$('entryRate').value=f.rate;updateEntryPreview()});['invoiceFarm','invoiceStart','invoiceEnd'].forEach(id=>$(id).addEventListener('change',updateInvoicePreview));$('historySearch').addEventListener('input',renderHistory);$('historyFarm').addEventListener('change',renderHistory);$('backupInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importBackup(f);e.target.value=''});window.addEventListener('resize',()=>activeView==='finance'&&drawChart());
load();render();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js?v=11.0.0').catch(()=>{});
})();
